# Generated by Django 6.0.4 on 2026-04-29 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='is_active_session',
            field=models.BooleanField(default=False),
        ),
    ]
