# Generated by Django 4.2.11 on 2026-04-29 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_voter_is_active_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='session_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
