# Generated by Django 4.2.11 on 2026-05-11 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_voter_session_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='course',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='year_level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
